package com.fileshare.common;


public enum PacketType {
// Auth
CLIENT_LOGIN, CLIENT_LOGIN_OK, CLIENT_LOGIN_FAIL,


// Listing
LIST_GROUPS, GROUPS_LIST, LIST_ENTRIES, ENTRIES_LIST,
USER_LIST_REQUEST, USER_LIST,

// FS ops
CREATE_FOLDER, CREATE_FOLDER_OK, CREATE_FOLDER_FAIL,
DELETE_ENTRY, DELETE_ENTRY_OK, DELETE_ENTRY_FAIL,

CREATE_GROUP_REQUEST, CREATE_GROUP_OK, CREATE_GROUP_FAIL,
JOIN_GROUP_REQUEST, JOIN_GROUP_OK, JOIN_GROUP_FAIL,
INVITE_MEMBER_REQUEST, INVITE_MEMBER_OK, INVITE_MEMBER_FAIL,
// Upload
START_UPLOAD, UPLOAD_READY, FILE_CHUNK, UPLOAD_DONE, UPLOAD_ERROR,



// Download
START_DOWNLOAD, DOWNLOAD_READY, DOWNLOAD_CHUNK, DOWNLOAD_DONE, DOWNLOAD_ERROR,


// Misc
ERROR, SUCCESS
}